### Create User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "asdf@asdf.com",
    "password": "P@ssw0rd"
}

###
GET http://localhost:3000/auth/2

###
GET http://localhost:3000/auth?email=myemail@example.com

###
DELETE http://localhost:3000/auth/1

### Update User
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "updated@email.com"
}